# see https://github.com/Fallen-Breath/smcr
listen: 0.0.0.0:7777
debug: false
routes:
  # regular
  - name: foo
    matches:
      - localhost:7777
    target: 127.0.0.1:25565

  - name: bar
    matches:
      - 127.0.0.1:7777
      - mc.example.com
    target: 127.0.0.1:25566
    mimic: mc.example.com:25566

  - name: default
    action: reject
    # reject_message: oops

srv_lookup_timeout: 3s
default_connect_timeout: 3s
