name: goreleaser

on:
  push:

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: fallenbreath
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare tags
        uses: actions/github-script@v6
        id: tags
        with:
          script: |
            let name = 'fallenbreath/smcr'
            let tags = []
            if (github.event_name == 'push' && github.ref.startsWith('refs/tags/v')) {
              tags.push(name + ':latest')
              tags.push(name + ':' + ref.slice('refs/tags/v'.length))
            } else {
              tags.push(name + ':nightly')
            }
            return tags.join('\n')
          result-encoding: string

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/386,linux/amd64,linux/arm64
          file: ./docker/Dockerfile
          context: .
          tags: ${{ steps.tags.outputs.result }}
          push: true
